
export const drawerWidth = 240;

export const formTypes = {

    newVehicle: 'NEW_VEHICLE',
    newUser: 'NEW_USER',
    newPenalty: 'NEW_PENALTY',
    newPrint: 'NEW_PRINT',
    login: 'LOGIN',
    signUp: 'SIGN_UP',
    forgotPassword: 'FORGOT_PASSWORD',
    newPassword: 'NEW_PASSWORD',
    newAutoGeneratedForm: 'NEW_AUTO_GENERATED_FORM',
    autoGenerateForm: 'AUTO_GENERATE_FORM',
}

export const pageType = {
    vehicle: {
        type: 'VEHICLE',
        sortByOptions: [
            "Plate Number",
            "creation date"
        ],
    },
    penalty: {
        type: 'PENALTY',
        sortByOptions: [
            "Plate Number", "receipt no", "owner name", "penalty date"
        ],
    },
    users: {
        type: 'USERS',
        sortByOptions: [
            "Name",
            "creation date"
        ],
    },
}


export const excelFileType = {
    //attached to excel to identify page type. for menu data, the added menu will be used as file type 
    vehicle: "VEHICLE",
    penalty: "PENALTY",
}
export const paymentStatus = ['Odendi','Beklemende',]

export const cancelationStatus = ["İPTAL EDİLDİ", "BEKLEMEDE"]

export const signUpTextfields  = [
    {
        placeholder: "Isim",
        name: "name",
        type: "text"

    },
    {
        placeholder: "Soyadı",
        name: "surname",
        type: "text"

    },
    {
        placeholder: "E-post",
        name: "email",
        type: "email"

    },
    {
        placeholder: "Parola",
        name: "password",
        type: "password"

    },
]


export const vehicleTextFields = [
    {
        placeholder: "Plaka No",
        name: "plate_number"

    },
    {
        placeholder: "Araç Grubu",
        name: "vehicle_group"

    },
    {
        placeholder: "Marka-Model",
        name: "brand_model"

    },
    {
        placeholder: "Şase No",
        name: "chassis_number"
    },
    {
        placeholder: "Motor No",
        name: "motor_number"
    },
    {
        placeholder: "Model Yılı",
        name: "model_year"
    },
    {
        placeholder: "Renk",
        name: "color"
    },
    {
        placeholder: "Dosya No",
        name: "file_number"
    },
    {
        placeholder: "Künye",
        name: "tag"
    },
    {
        placeholder: "Demirbaş No",
        name: "asset_number"
    },
    {
        
        placeholder: "CEZA TARİHİ",
        name: "delivery_date"
    }
]

export const vehicleSelectFields = [

    {
        name: "unit_garage_status",
        label: "Birim",
        menuItem: [

            {
                value: "İstaç A.Ş"
            },
            {
                value: "İgdaş A.Ş"
            },
            {
                value: "Avrupa yakası Zabıta",
            },
            {
                value: "Avrupa yakası Mezarlıklar",
            },
            {
                value: "Makine ikmal",
            },
            {
                value: "Destek Hizmetleri",
            }, 
            {
                value: "İsbak A.Ş",
            },
            {
                value: "Anadolu yakası Zabıta",
            },
            {
                value: "Anadolu yakası Mezarlıklar",
            },
            {
                value: "Ağaç A.Ş",
            },
            {
                value: "İsfalt A.Ş",
            },
            
        ]
    },
    {
        name: "vehicle_status",
        label: "araç durum",
        menuItem: [
            {
                value: 'Serviste',
            },
            {
                value : 'zimmetli',
            },
            {
                value : 'bakimda',
            },
            {
                value : 'zimmetli degil',
            }
        ]
    },
    {
        name: "vehicle_type",
        label: "araç tipi",
        menuItem: [
        
            {
                value: "kiralik"
            },
            {
                value: "Ö.MAKBUZ"
            },
            {
                value: "ihale yolu"
            },
            {
                value: "Protokol"
            },
            {
                value: "yedek"
            },
        ]
    },

]


export const penaltyTextFields = [
    
    {
        placeholder: "PLAKA NO",
        name: "plate_number",
        type: "text"

    },
    {
        placeholder: "MAKBUZ",
        name: "receipt_number",
        type: "text"

    },
    {
        placeholder: "CEZA TARİHİ",
        name: "penalty_date",
        type: "text"

    },
    {
        placeholder: "CEZA SAATİ ",
        name: "penalty_hour",
        type: "text"

    },
    {
        placeholder: "TEBLİĞ TARİHİ ",
        name: "notification_date",
        type: "text"

    },
    {
        placeholder: "CEZA TUTAR",
        name: "penalty",
        type: "text"

    },
    {
        placeholder: "PESİN TUTAR ",
        name: "payment_amount",
        type: "text"

    },
    {
        placeholder: "CEZA MADDESİ ",
        name: "penalty_article",
        type: "text"

    },
    {
        placeholder: "BİRİM  ",
        name: "unit",
        type: "text"

    },
    {
        placeholder: "İSİM-SOYİSİM ",
        name: "name",
        type: "text"

    },
    {
        placeholder: "İBB KAYIT TARİHİ ",
        name: "registration_date",
        type: "text"

    },
    {
        placeholder: "BİRİME GELİŞ TARİHİ",
        name: "arrival_date",
        type: "text"

    },
    {
        placeholder: "İBB NO",
        name: "imm_no",
        type: "text"

    },
    {
        placeholder: "TALEP NO",
        name: "request_no",
        type: "text"

    },
    {
        placeholder: "BİRİM NO",
        name: "unit_no",
        type: "text"

    },
    {
        placeholder: "FİRMA",
        name: "company",
        type: "text"

    },
    {
        placeholder: "KARAR TARİHİ",
        name: "decision_date",
        type: "text"

    },
    {
        placeholder: "ÖDEME TARİHİ",
        name: "payment_date",
        type: "text"

    },
    {
        placeholder: "ÖDEME YAPAN",
        name: "paying",
        type: "text"

    },
    {
        placeholder: "NOT ",
        name: "note",
        type: "text"

    },
]


export const otherFields = [
    {
        name: 'delivery_date',
        placeholder: 'teslim tarihi'
    },
    {
        name: 'updated_at',
        placeholder: 'güncellendi'
    },
    {
        name: 'created_at',
        placeholder: 'oluşturulma tarihi'
    },
    {
        name: 'notification_date',
        placeholder: 'TEBLİG TARİHİ'
    },
    {
        name: 'status',
        placeholder: 'ÖDEME DURUMU'
    },
    {
        name: 'payment_date',
        placeholder: 'ÖDEME TARİHİ'
    },
    {
        name: 'penalty_date',
        placeholder: 'CEZA TARİHİ'
    },
    {
        name: 'penalty_hour',
        placeholder: 'CEZA-SAAT'
    },
    {
        name: 'role',
        placeholder: 'rol'
    },
    {
        name: "vehicle_type",
        placeholder: "Araç Tipi",
    },
    {
        
        name: "unit_garage_status",
        placeholder: "Birim",
    },
    {
        
        name: "vehicle_status",
        placeholder: "araç durum",
    },
    {
        
        name: "equipment",
        placeholder: "araç ekipmanları",
    },
    {
        
        name: "cancelation_status",
        placeholder: "İptal durum",
    },
    {
        name:'image_url',
        placeholder: 'resim'
    }
    
]

export const __Dates = [
    {
        
        name: "Monday",
        placeholder: "Pazartesi",
    },
    {
        
        name: "Tuesday",
        placeholder: "Salı",
    },
    {
        
        name: "Wednesday",
        placeholder: "Çarşamba",
    },
    {
        
        name: "Thursday",
        placeholder: "Perşembe",
    },
    {
        
        name: "Friday",
        placeholder: "Cuma",
    },
    {
        
        name: "Saturday",
        placeholder: "Cumartesi",
    },
    {
        
        name: "Sunday",
        placeholder: "Pazar",
    },
]


export const printData = [

    {
        name: "PLAKA",
        placeholder: "PLAKA",
        type: "text",
        
    },
    {
        name: "CEZA_NO",
        placeholder: "CEZA NO",
        type: "text",
        
    },
    {
        name: "CEZA_TARİHİ",
        placeholder: "CEZA TARİHİ",
        type: "text",
        
    },
    {
        name: "CEZA_SAATİ",
        placeholder: "CEZA SAATİ",
        type: "text",
        
    },
    {
        name: "BİRİM",
        placeholder: "BİRİM",
        type: "text",
        
    },
    {
        name: "TESLİM_EDEN",
        placeholder: "TESLİM EDEN",
        type: "text",
        
    },
    {
        name: "TESLİM_ALAN",
        placeholder: "TESLİM ALAN",
        type: "text",
        
    },
    {
        name: "TALEP_NO",
        placeholder: "TALEP NO",
        type: "text",
        
    },


]